spring:
  application:
    name: itachallenge-user
  jmx:
    enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/itac-users

springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

server:
  port: 8762

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false




logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.itachallenges]": INFO
  pattern:
  # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: itachallenge-user.log

